// Verklig webbläsare och Kundstarts kundserver. Syntetiska uppgifter; inga AI-anrop.
import { spawn } from 'node:child_process';
import { once } from 'node:events';
import { readFile } from 'node:fs/promises';
import { resolve } from 'node:path';
import { chromium } from 'playwright';
import assert from 'node:assert/strict';
const root=resolve(process.argv[2]||'.');
const child=spawn(resolve(root,'.venv/bin/python'),['-B','kontroller/rokprov/revision/prov_kundstart_http.py','--provserver'],{cwd:root,stdio:['ignore','pipe','pipe']});
let browser,stderr='';child.stderr.on('data',b=>stderr+=b);
try{
 const init=await new Promise((res,rej)=>{let s='';const timer=setTimeout(()=>rej(Error('Provservern startade inte')),10000);child.on('exit',()=>{clearTimeout(timer);rej(Error('Provservern avslutades: '+stderr));});child.stdout.on('data',b=>{s+=b;if(s.includes('\n')){clearTimeout(timer);try{res(JSON.parse(s.split('\n')[0]));}catch(e){rej(e);}}});});
 const origin=`http://127.0.0.1:${init.port}`;
 browser=await chromium.launch({headless:true});const page=await browser.newPage();const errors=[];page.on('pageerror',e=>errors.push(e.message));
 await page.route('**/*',r=>new URL(r.request().url()).origin===origin?r.continue():r.abort());
 await page.goto(`${origin}/#arende=${init.arende}&nyckel=${init.nyckel}`);
 await page.getByRole('button',{name:'Spara och fortsätt',exact:true}).waitFor();
 assert.equal(new URL(page.url()).hash,'');
 for(const width of [320,390,768,1280,1440]){
  await page.setViewportSize({width,height:900});
  assert(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth),'spill vid '+width);
  const box=await page.getByRole('button',{name:'Spara och fortsätt',exact:true}).boundingBox();assert(box.height>=44);
  await page.evaluate(()=>scrollTo(0,0));
  if(process.env.NWP_UI_BEVISET&&[390,1440].includes(width))await page.screenshot({path:process.env.NWP_UI_BEVISET.replace(/\.png$/,`-${width}.png`),fullPage:true});
 }
 const axeBytes=await readFile(resolve(root,'kontroller/node_modules/axe-core/axe.min.js'));
 await page.route(origin+'/prov-axe.js',r=>r.fulfill({contentType:'text/javascript',body:axeBytes}));
 await page.addScriptTag({url:origin+'/prov-axe.js'});
 const axe=await page.evaluate(()=>window.axe.run(document,{runOnly:{type:'tag',values:['wcag2a','wcag2aa','wcag21aa','wcag22aa']}}));
 assert.deepEqual(axe.violations.map(v=>v.id),[],'axe');
 let tappaMeddelande=true,tappaUppgift=true;const payloads=[];
 await page.route(origin+'/api/arende/'+init.arende,async route=>{
  if(route.request().method()!=='POST')return route.continue();
  const p=route.request().postDataJSON();payloads.push(p);
  const tappa=(p.handling==='meddelande'&&tappaMeddelande)||(p.handling==='uppgift'&&tappaUppgift);
  if(p.handling==='meddelande')tappaMeddelande=false;if(p.handling==='uppgift')tappaUppgift=false;
  if(tappa){await route.fetch();return route.fulfill({status:503,contentType:'application/json',body:JSON.stringify({fel:'Syntetiskt tappat svar efter lagring.'})});}
  return route.continue();
 });
 await page.getByLabel('Ditt svar',{exact:true}).fill('Vi behöver hjälp med en tydlig webbplats.');
 const send=page.getByRole('button',{name:'Spara och fortsätt',exact:true});await send.focus();await page.keyboard.press('Enter');
 await page.getByRole('status').filter({hasText:'Syntetiskt tappat svar'}).waitFor();
 await page.getByRole('button',{name:'Hämta senaste uppdateringen',exact:true}).click();
 await page.getByRole('status').filter({hasText:'Senaste versionen'}).waitFor();
 await page.getByLabel('Uppgift',{exact:true}).fill('Vi erbjuder en avgränsad tjänst.');
 await page.getByRole('button',{name:'Spara uppgiften',exact:true}).click();
 await page.getByRole('status').filter({hasText:'Syntetiskt tappat svar'}).waitFor();
 await page.reload();await page.getByRole('button',{name:'Spara och fortsätt',exact:true}).waitFor();
 assert.equal(await page.getByLabel('Ditt svar',{exact:true}).inputValue(),'Vi behöver hjälp med en tydlig webbplats.');
 assert.equal(await page.getByLabel('Uppgift',{exact:true}).inputValue(),'Vi erbjuder en avgränsad tjänst.');
 await send.click();await page.getByRole('status').filter({hasText:'Sparat.'}).waitFor();
 const svar=payloads.filter(p=>p.handling==='meddelande');assert.equal(svar[0].operation,svar[1].operation);
 assert.equal(await page.locator('#meddelanden article').count(),1);
 await page.getByRole('button',{name:'Spara uppgiften',exact:true}).click();
 await page.getByRole('status').filter({hasText:'Sparat.'}).waitFor();
 const uppgifter=payloads.filter(p=>p.handling==='uppgift');assert.equal(uppgifter[0].operation,uppgifter[1].operation,'ny uppgift får samma operations-id efter svarsfel och annan handling');
 assert.equal(await page.locator('#uppgifter article').count(),1);
 await page.getByRole('button',{name:'Rätta uppgiften',exact:true}).click();
 await page.getByLabel('Uppgift',{exact:true}).fill('Mitt utkast från den första fliken.');
 const headers={Authorization:'Bearer '+init.nyckel,Origin:origin};
 const fore=await (await page.request.get(origin+'/api/arende/'+init.arende,{headers})).json();
 const annat=await page.request.post(origin+'/api/arende/'+init.arende,{headers,data:{revision:fore.revision,operation:'annan-flik-prov',handling:'uppgift',data:{...uppgifter[0].data,text:'Rättelsen från den andra fliken.'}}});
 assert.equal(annat.status(),200);
 await page.getByRole('button',{name:'Hämta senaste uppdateringen',exact:true}).click();
 await page.getByRole('status').filter({hasText:'Senaste versionen'}).waitFor();
 await page.getByRole('button',{name:'Spara uppgiften',exact:true}).click();
 await page.getByRole('status').filter({hasText:'Jämför den med ditt bevarade utkast'}).waitFor();
 assert.equal(payloads.at(-1).revision,fore.revision,'hämtning flyttar inte utkastets basrevision');
 assert.equal(await page.getByLabel('Uppgift',{exact:true}).inputValue(),'Mitt utkast från den första fliken.');
 assert((await page.locator('#uppgifter').innerText()).includes('Rättelsen från den andra fliken.'));
 await page.getByRole('button',{name:'Jag har jämfört med senaste uppgiften och vill behålla mitt utkast',exact:true}).click();
 await page.getByRole('button',{name:'Spara uppgiften',exact:true}).click();
 await page.getByRole('status').filter({hasText:'Sparat.'}).waitFor();
 await page.getByLabel('Ditt svar',{exact:true}).fill('Ytterligare ett osparat svar.');
 const antal=payloads.length;
 await page.evaluate(()=>{Storage.prototype.setItem=function(){throw Error('syntetiskt fullt lagringsutrymme');};});
 await send.click();await page.getByRole('status').filter({hasText:'kan inte bevara utkastet'}).waitFor();
 assert.equal(payloads.length,antal,'inget inskick när operations-id inte kan bevaras');
 await page.reload();await page.getByRole('button',{name:'Spara uppgiften',exact:true}).waitFor();
 await page.route(origin+'/api/arende/'+init.arende,r=>r.fulfill({status:403,contentType:'application/json',body:JSON.stringify({fel:'Åtkomsten har upphört.'})}));
 await page.getByRole('button',{name:'Hämta senaste uppdateringen',exact:true}).click();
 await page.getByRole('status').filter({hasText:'Åtkomsten har upphört'}).waitFor();
 assert(await page.locator('#arbete').isHidden(),'gamla kunduppgifter visas inte efter nekad åtkomst');
 await page.goto('about:blank');
 await page.goto(`${origin}/#arende=${init.forslag_arende}&nyckel=${init.forslag_nyckel}`);
 await page.getByRole('button',{name:'Använd som utgångspunkt för en uppgift',exact:true}).click();
 await page.getByRole('button',{name:'Spara uppgiften',exact:true}).click();
 await page.getByRole('status').filter({hasText:'Sparat.'}).waitFor();
 assert((await page.locator('#uppgifter').innerText()).includes('Ett tydligare erbjudande.'));
 await page.getByRole('button',{name:'Svara på kompletteringen',exact:true}).click();
 await page.getByLabel('Ditt svar',{exact:true}).fill('Vi vet inte än. Hjälp oss välja mottagare.');
 await page.getByLabel('Hur vill du svara på kompletteringen?',{exact:true}).selectOption('vet_inte');
 await page.reload();await page.getByRole('button',{name:'Spara och fortsätt',exact:true}).waitFor();
 assert.equal(await page.getByLabel('Ditt svar',{exact:true}).inputValue(),'Vi vet inte än. Hjälp oss välja mottagare.');
 assert.equal(await page.getByLabel('Hur vill du svara på kompletteringen?',{exact:true}).inputValue(),'vet_inte');
 await page.getByRole('button',{name:'Spara och fortsätt',exact:true}).click();
 await page.getByRole('status').filter({hasText:'Sparat.'}).waitFor();
 const svarad=await (await page.request.get(origin+'/api/arende/'+init.forslag_arende,{headers:{Authorization:'Bearer '+init.forslag_nyckel}})).json();
 assert.equal(svarad.returfragor.mottagare.status,'vet_inte');assert.equal(svarad.meddelanden.at(-1).fraga,'mottagare');
 assert(await page.locator('#svarar-pa').isHidden());
 await page.getByText('Berätta om en funktion eller koppling ni behöver',{exact:true}).click();
 await page.getByLabel('Vad vill ni kunna göra?',{exact:true}).fill('Besökaren ska kunna boka en ledig tid.');
 await page.reload();await page.getByRole('button',{name:'Spara och fortsätt',exact:true}).waitFor();
 await page.getByText('Berätta om en funktion eller koppling ni behöver',{exact:true}).click();
 assert.equal(await page.getByLabel('Vad vill ni kunna göra?',{exact:true}).inputValue(),'Besökaren ska kunna boka en ledig tid.');
 await page.getByRole('button',{name:'Spara funktionsbehovet',exact:true}).click();
 await page.getByRole('status').filter({hasText:'Sparat.'}).waitFor();
 assert((await page.locator('#integrationsstatus').innerText()).includes('ert konto: inte kontrollerat'));
 await page.getByLabel('Välj material',{exact:true}).setInputFiles({name:'syntetiskt-material.txt',mimeType:'text/plain',buffer:Buffer.from('Endast syntetiskt provmaterial.')});
 await page.getByRole('button',{name:'Ladda upp',exact:true}).click();await page.getByRole('status').filter({hasText:'Sparat.'}).waitFor();
 await page.getByRole('button',{name:'Beskriv användningsrätten',exact:true}).click();
 await page.getByLabel('Får materialet användas på webbplatsen?',{exact:true}).selectOption('saknar_ratt');
 await page.getByLabel('Beskriv källan och vad ni vet om tillståndet',{exact:true}).fill('Det är ett prov, inte material för publicering.');
 await page.reload();await page.getByRole('button',{name:'Spara rättighetsbeskedet',exact:true}).waitFor();
 assert.equal(await page.getByLabel('Får materialet användas på webbplatsen?',{exact:true}).inputValue(),'saknar_ratt');
 await page.getByRole('button',{name:'Spara rättighetsbeskedet',exact:true}).click();await page.getByRole('status').filter({hasText:'Sparat.'}).waitFor();
 assert((await page.locator('#material').innerText()).includes('Användningsrätt saknas'));
 await page.goto('about:blank');await page.goto(`${origin}/#arende=${init.konflikt_arende}&nyckel=${init.konflikt_nyckel}`);
 await page.getByRole('button',{name:'Klarlägg de motstridiga uppgifterna',exact:true}).click();
 await page.getByLabel('Uppgift',{exact:true}).fill('Den gemensamt klarlagda uppgiften.');
 await page.getByLabel('Hur har ni klarlagt motsägelsen?',{exact:true}).fill('Båda provrollerna har stämt av detta.');
 await page.reload();await page.getByRole('button',{name:'Spara klarläggandet',exact:true}).waitFor();
 assert.equal(await page.getByLabel('Hur har ni klarlagt motsägelsen?',{exact:true}).inputValue(),'Båda provrollerna har stämt av detta.');
 await page.getByRole('button',{name:'Spara klarläggandet',exact:true}).click();await page.getByRole('status').filter({hasText:'Sparat.'}).waitFor();
 assert(!(await page.locator('#uppgifter').innerText()).includes('behöver klarläggas'));
 await page.goto('about:blank');await page.goto(`${origin}/#arende=${init.konflikt_arende}&nyckel=${init.lasare_nyckel}`);
 await page.getByText('Din länk ger läsåtkomst.',{exact:true}).waitFor();
 assert(await page.getByRole('button',{name:'Spara och fortsätt',exact:true}).isDisabled());
 assert(await page.getByRole('button',{name:'Skicka beställningsförfrågan',exact:true}).isDisabled());
 assert(await page.getByRole('button',{name:'Rätta uppgiften',exact:true}).isDisabled());
 await page.setViewportSize({width:390,height:900});await page.route(origin+'/prov-text.css',r=>r.fulfill({contentType:'text/css',body:'html{font-size:200%}'}));await page.addStyleTag({url:origin+'/prov-text.css'});
 assert(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth),'textförstoring');
 assert.deepEqual(errors,[]);
 console.log(JSON.stringify({bredder:[320,390,768,1280,1440],axe_fynd:axe.violations.length,tangentbord:true,
   omforsok_samma_operation:true,svar_bevarat_vid_omladdning:true,api:'riktig lokal server, endast syntetiska ärenden'}));
}finally{
 await browser?.close();child.kill('SIGTERM');
 if(child.exitCode===null){const timer=setTimeout(()=>child.kill('SIGKILL'),3000);try{await once(child,'exit');}finally{clearTimeout(timer);}}
}
